#!/bin/sh
# Kuberentes Tools
#
# https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-on-linux
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl
#
# (cloux@rote.ch)

printf 'Install kubernetes tools - kubectl, kubeadm, kubelet\n\n'

if [ $(id -u) -ne 0 ]; then printf 'Need to be root!\n'; exit 1; fi

# check versions
if [ "$(command -v kubectl)" ]; then
	CURRENT=$(kubectl version 2>/dev/null | sed 's/.*GitVersion: *"//' | grep -o '^[^"]*')
	printf 'Installed version: %s\n' "$CURRENT" 
fi
printf '   Latest version: '
LATEST_STABLE_LINK="https://storage.googleapis.com/kubernetes-release/release/stable.txt"
LATEST=$(wget -q "$LATEST_STABLE_LINK" -O - 2>/dev/null)
if [ -z "$LATEST" ]; then
	printf 'ERROR: latest version check failed.\n'
	exit
fi
printf '%s\n\n' "$LATEST"
if [ "$CURRENT" = "$LATEST" ]; then
	printf 'Up to date, nothing to do.\n'
	exit
fi

# download
cd /tmp || exit 1
KUBECTL_LINK="https://storage.googleapis.com/kubernetes-release/release/$LATEST/bin/linux/amd64/kubectl"
KUBEADM_LINK="https://storage.googleapis.com/kubernetes-release/release/$LATEST/bin/linux/amd64/kubeadm"
KUBELET_LINK="https://storage.googleapis.com/kubernetes-release/release/$LATEST/bin/linux/amd64/kubelet"
wget -4 -N -nd --progress=dot:giga "$KUBECTL_LINK" "$KUBEADM_LINK" "$KUBELET_LINK"
if [ $? -ne 0 ] || [ ! -s kubectl ]; then
	printf 'ERROR: download failed.\n'
	exit
fi

# install
printf 'Installing to /usr/local/bin/ ...\n'
chmod 755 kubectl kubeadm kubelet 2>/dev/null
mv -f -t /usr/local/bin/ kubectl kubeadm kubelet || exit 1

# shell completions
if [ -d /usr/share/bash-completion/completions ]; then
	kubectl completion bash 2>/dev/null > /usr/share/bash-completion/completions/kubectl
	kubeadm completion bash 2>/dev/null > /usr/share/bash-completion/completions/kubeadm
fi
if [ -d /usr/share/zsh/vendor-completions ]; then
	kubectl completion zsh 2>/dev/null > /usr/share/zsh/vendor-completions/_kubectl
	kubeadm completion zsh 2>/dev/null > /usr/share/zsh/vendor-completions/_kubeadm
fi
printf '\nDONE\n'
