#!/bin/sh
# Install Google Earth (amd64)
#
# (cloux@rote.ch)

if [ $(id -u) -ne 0 ]; then printf 'Need to be root!\n'; exit 1; fi
if [ -z "$(command -v dpkg)" ]; then
	printf 'ERROR: dpkg is missing, DEB packages can not be installed.\n'
	exit 1
fi

ARCHIVE_DIR=/var/cache/sin
[ -d "$ARCHIVE_DIR" ] || mkdir -p "$ARCHIVE_DIR"
cd $ARCHIVE_DIR || exit 1

DEB_FILE=google-earth-pro-stable_current_amd64.deb
[ -f "$DEB_FILE" ] && MTIME_BEFORE=$(stat --format=%Y "$DEB_FILE")
wget -4 -N -nd --progress=dot:giga https://dl.google.com/dl/earth/client/current/$DEB_FILE || exit 1
MTIME_NOW=$(stat --format=%Y "$DEB_FILE")
if [ "$MTIME_BEFORE" = "$MTIME_NOW" ]; then
	printf 'Latest GoogleEarth release (%s) already downloaded, nothing to do.\n\n' \
	"$(stat --format=%y "$DEB_FILE" | grep -o '^[^ ]*')"
	exit
fi

dpkg -i "$DEB_FILE"
if [ $? -ne 0 ]; then
	if [ "$(command -v aptitude)" ]; then
		APTINST=aptitude
	elif [ "$(command -v apt-get)" ]; then
		APTINST=apt-get
	fi
	if [ "$APTINST" ]; then
		$APTINST -f --assume-yes -o Dpkg::Use-Pty=0 install
	else
		printf 'ERROR: DEB installer not found, dependency installation failed.\n'
		exit 1
	fi
fi

printf '\nDONE\n'

