#!/bin/sh
# Install Jenkins
# (cloux@rote.ch)

if [ $(id -u) -ne 0 ]; then printf "Need to be root!\n"; exit 1; fi

cd /opt || exit 1
printf "Downloading Jenkins into /opt ... \n"
wget -N -4 --progress=dot:giga http://mirrors.jenkins.io/war/latest/jenkins.war || exit 1

printf "Start Jenkins by running:\n\n  java -jar /opt/jenkins.war --httpPort=9090\n\nDONE\n"
