#!/bin/sh
# Install Skype from deb package
#
# (cloux@rote.ch)

if [ $(id -u) -ne 0 ]; then printf 'Need to be root!\n'; exit 1; fi
if [ -z "$(command -v dpkg)" ]; then
	printf 'ERROR: dpkg is missing, Skype DEB package can not be installed.\n'
	exit 1
fi
ARCHIVE_DIR=/var/cache/sin
[ -d "$ARCHIVE_DIR" ] || mkdir -p "$ARCHIVE_DIR"
cd $ARCHIVE_DIR || exit 1

DEB_FILE=skypeforlinux-64.deb

[ -f "$DEB_FILE" ] && MTIME_BEFORE=$(stat --format=%Y "$DEB_FILE")
wget -4 -N -nd --progress=dot:giga https://go.skype.com/$DEB_FILE || exit 1
MTIME_NOW=$(stat --format=%Y "$DEB_FILE")
if [ "$MTIME_BEFORE" = "$MTIME_NOW" ]; then
	printf 'Latest Skype release (%s) already downloaded, nothing to do.\n\n' \
	"$(stat --format=%y "$DEB_FILE" | grep -o '^[^ ]*')"
	exit
fi

export DEBIAN_FRONTEND=noninteractive
dpkg --force-confdef -i "$DEB_FILE" || exit 1
if [ $? -ne 0 ]; then
	if [ "$(command -v aptitude)" ]; then
		APTINST=aptitude
	elif [ "$(command -v apt-get)" ]; then
		APTINST=apt-get
	fi
	if [ "$APTINST" ]; then
		$APTINST -f --assume-yes -o Dpkg::Use-Pty=0 install
	else
		printf 'ERROR: DEB installer not found, dependency installation failed.\n'
		exit 1
	fi
fi

printf '\nBy using Skype, you agree to\n'
printf '\nSkype Data Collection: https://go.skype.com/tou\n'
printf '\nYour-Privacy-Is-Gone Terms: https://go.skype.com/privacy\n'

printf '\nDONE\n'
