#!/bin/sh

DOWNLOAD_PAGE="https://www.java.com/en/download/linux_manual.jsp"

if [ $(id -u) -ne 0 ]; then printf 'Need to be root!\n'; exit 1; fi
[ "$(command -v apt-get)" ] || exit 1
if [ ! -x "$(command -v make-jpkg)" ]; then
	printf 'Installing java-package ...\n'
	apt-get -o Dpkg::Use-Pty=0 update
	apt-get --assume-yes -o Dpkg::Use-Pty=0 install java-package || exit 1
fi

ARCHIVE_DIR=/var/cache/sin
TMP_DIR=$(mktemp -d)
trap "rm -rf $TMP_DIR" 0 1 2 3 9 15
chmod 777 $TMP_DIR
cd $TMP_DIR

printf 'Searching for Oracle JRE update ...\n'

DOWNLOAD_INFO="$(wget -q4 -O - "$DOWNLOAD_PAGE" 2>/dev/null)"
[ "$DOWNLOAD_INFO" ] || exit 1
INSTALLER_LINK=$(printf '%s' "$DOWNLOAD_INFO" | \
 grep 'Linux x64' | grep -v RPM | grep http | head -n 1 | grep -o 'href="[^"]*' | grep -o 'http.*')
if [ -z "$INSTALLER_LINK" ]; then
	printf "not found\n"
	exit 1
fi
VER_MAJ=$(printf '%s' "$DOWNLOAD_INFO" | grep -io 'Version[ 0-9]*' | grep -o '[0-9]*')
VER_UPD=$(printf '%s' "$DOWNLOAD_INFO" | grep -io 'Update[ 0-9]*' | grep -o '[0-9]*')
INSTALLER_FILE="jre-${VER_MAJ}u${VER_UPD}-linux-x64.tar.gz"
DEB_FILE="oracle-java${VER_MAJ}-jre_${VER_MAJ}u${VER_UPD}_amd64.deb"
printf 'Latest Oracle JRE version: %su%s\n\n' "$VER_MAJ" "$VER_UPD"

if [ -f "$ARCHIVE_DIR/$DEB_FILE" ]; then
	printf 'Package available: %s/%s\n' "$ARCHIVE_DIR" "$DEB_FILE"
	exit
fi

wget -4 -nd --progress=dot:giga -O "$INSTALLER_FILE" "$INSTALLER_LINK" || exit 1
[ -s "$INSTALLER_FILE" ] || exit 1
su $(id -un 1000) -c "yes 2>/dev/null | make-jpkg $INSTALLER_FILE 2>/dev/null"
[ -s "$DEB_FILE" ] || exit 1
[ -d "$ARCHIVE_DIR" ] && cp "$DEB_FILE" "$ARCHIVE_DIR"
dpkg -i "$ARCHIVE_DIR"/"$DEB_FILE" || exit 1

printf '\nDONE\n'
