#!/bin/sh
#
# Install WireGuard - Secure VPN Tunnel
# https://www.wireguard.com
#
# (cloux@rote.ch)

# need to be root
if [ $(id -u) -ne 0 ]; then printf 'Need to be root!\n'; exit 1; fi

# get the source
cd /usr/src
if [ -d WireGuard ]; then
	# NOTE: do not pull, this repository introduces conflicts on a regular basis
	rm -rf WireGuard
else
	# install dependencies
	export DEBIAN_FRONTEND=noninteractive
	apt-get --assume-yes -o Dpkg::Use-Pty=0 install git libmnl-dev libelf-dev \
	  build-essential pkg-config || exit 1
fi
# clone repo
git clone --depth 1 https://git.zx2c4.com/WireGuard || exit 1
cd WireGuard/src

# compile & install
export LC_ALL=C
export LANG=C
make || exit 1
make install || exit 1
make clean >/dev/null

printf '\nDONE\n'
