#!/bin/sh
# install fstrim cronjob for SSD drives

if [ $(id -u) -ne 0 ]; then printf 'Need to be root!\n'; exit 1; fi

if ls -1 /etc/cron.weekly 2>/dev/null | grep -q trim; then
	printf 'Trim cronjob is already present, nothing to do.\n'
	exit
fi

cp -u ${0%/*}/fstrim /etc/cron.weekly/fstrim
