#!/bin/sh
# Minikube - tool to run kuberentes locally
#
# (cloux@rote.ch)

printf 'Install minikube\n\n'

if [ $(id -u) -ne 0 ]; then printf 'Need to be root!\n'; exit 1; fi

# check dependencies
for DEP in wget jq; do
	if ! command -v "$DEP" >/dev/null; then
		printf 'ERROR: Please install "%s" to continue.\n' "$DEP"
		exit 1
	fi
done

# check versions
if [ "$(command -v minikube)" ]; then
	INST_VERSION=$(minikube version 2>/dev/null | grep version | grep -o '[0-9.]*$')
	printf 'Installed version: %s\n' "$INST_VERSION"
fi
printf '   Latest version: '
JSON_FILE=$(mktemp)
LATEST_STABLE_LINK="https://api.github.com/repos/kubernetes/minikube/releases/latest"
wget -q "$LATEST_STABLE_LINK" -O "$JSON_FILE" 2>/dev/null
LATEST_VERSION=$(jq -r '.name' "$JSON_FILE" | grep -o '[0-9.]*')
LATEST_LINK=$(jq -r '.assets[].browser_download_url' "$JSON_FILE" | grep -i $(uname -s))
rm "$JSON_FILE"
if [ -z "$LATEST_VERSION" ]; then
	printf 'ERROR: latest version check failed.\n'
	exit
fi
printf '%s\n\n' "$LATEST_VERSION"
if [ "$INST_VERSION" ] && [ "$LATEST_VERSION" = "$INST_VERSION" ]; then
	printf 'Up to date, nothing to do.\n'
	exit
fi

# download
cd /tmp || exit 1
MINIKUBE_LINK="https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
wget -4 -N -nd --progress=dot:giga "$MINIKUBE_LINK"
if [ $? -ne 0 ] || [ ! -s minikube-linux-amd64 ]; then
	printf 'ERROR: download failed.\n'
	exit
fi

# install
printf 'Installing to /usr/local/bin/ ...\n'
chmod 755 minikube-linux-amd64
mv -f minikube-linux-amd64 /usr/local/bin/minikube || exit 1

# shell completions
[ -d /usr/share/bash-completion/completions ] &&
	minikube completion bash 2>/dev/null > /usr/share/bash-completion/completions/minikube
[ -d /usr/share/zsh/site-functions ] &&
	minikube completion zsh 2>/dev/null > /usr/share/zsh/site-functions/_minikube

printf '\nDONE\n'
