#!/bin/sh
# Podman uninstallation
#
# (cloux@rote.ch)

printf 'Remove podman ...\n'

if [ $(id -u) -ne 0 ]; then printf '\nNeed to be root!\n'; exit 1; fi

rm -rfv /usr/bin/podman* /usr/bin/conmon /usr/share/man/man[15]/podman* \
  /etc/containers* /usr/src/containers* /usr/share/containers* /var/lib/containers* \
  /usr/share/zsh/site-functions/_podman /usr/share/bash-completion/completions/podman

printf 'DONE\n'
