#!/bin/sh
#
# Check the latest kernel version on kernel.org
#
# (cloux@rote.ch)

MODULE_PATH=$(realpath "${0%/*}" 2>/dev/null)

if [ ! -x "${MODULE_PATH}/install" ]; then
	printf 'Error: %s not found\n' "${MODULE_PATH}/install"
	exit 1
fi

"${MODULE_PATH}/install" -c
