#!/bin/sh
#
# GitAhead is a graphical Git client for Linux, Winblows and MacOS.
# https://gitahead.github.io/gitahead.com/
#
# (cloux@rote.ch)

if [ $(id -u) -ne 0 ]; then printf 'Need to be root!\n'; exit 1; fi

# check dependencies
for DEP in wget jq; do
	if ! command -v "$DEP" >/dev/null; then
		printf 'ERROR: Please install "%s" to continue.\n' "$DEP"
		exit 1
	fi
done

# check version
if [ -x /opt/GitAhead/GitAhead ]; then
	INST_VERSION=$(/opt/GitAhead/GitAhead --version 2>/dev/null | grep -o '[0-9][0-9.]*[0-9]')
	printf ' Instaled version: %s\n' "$INST_VERSION"
fi
printf '   Latest version: '
JSON_FILE=$(mktemp)
wget -q "https://api.github.com/repos/gitahead/gitahead/releases/latest" -O "$JSON_FILE" 2>/dev/null
LATEST_VERSION=$(jq -r '.name' "$JSON_FILE" | grep -o '[^a-z]*')
LATEST_LINK=$(jq -r '.assets | map(select(.content_type == "application/x-sh"))[0] | .browser_download_url' "$JSON_FILE")
rm "$JSON_FILE"
if [ -z "$LATEST_VERSION" ]; then
	printf "ERROR: latest version check failed.\n"
	exit
fi
printf '%s\n\n' "$LATEST_VERSION"
if [ "$INST_VERSION" ] && [ "$LATEST_VERSION" = "$INST_VERSION" ]; then
	printf 'GitAhead is up to date.\n'
	exit
fi

# install
cd /opt
wget -4 -r -nd -nc --progress=dot:giga $LATEST_LINK || exit 1
LATEST_FILE=$(printf '%s' "$LATEST_LINK" | grep -o '[^/]*$')
[ -s "$LATEST_FILE" ] || exit 1

chmod 755 "$LATEST_FILE"
yes | ./"$LATEST_FILE"
rm -f ./"$LATEST_FILE"

if [ -s /opt/GitAhead/GitAhead ]; then
	mv -f /root/.local/share/applications/gitahead.desktop /usr/share/applications/
	cp -u /root/.local/share/icons/hicolor/16x16/apps/gitahead.png /usr/share/icons/hicolor/16x16/apps/
	cp -u /root/.local/share/icons/hicolor/32x32/apps/gitahead.png /usr/share/icons/hicolor/32x32/apps/
	cp -u /root/.local/share/icons/hicolor/64x64/apps/gitahead.png /usr/share/icons/hicolor/64x64/apps/
	cp -u /root/.local/share/icons/hicolor/128x128/apps/gitahead.png /usr/share/icons/hicolor/128x128/apps/
	cp -u /root/.local/share/icons/hicolor/256x256/apps/gitahead.png /usr/share/icons/hicolor/256x256/apps/
	cp -u /root/.local/share/icons/hicolor/512x512/apps/gitahead.png /usr/share/icons/hicolor/512x512/apps/
	ln -sf /opt/GitAhead/GitAhead /usr/local/bin/
fi

printf '\nDONE\n'
