#!/bin/sh
#
# GitAhead is a graphical Git client for Linux, Winblows and MacOS.
# https://gitahead.github.io/gitahead.com/
#
# (cloux@rote.ch)

if [ $(id -u) -ne 0 ]; then printf 'Need to be root!\n'; exit 1; fi

if [ -x /opt/GitAhead/GitAhead ]; then
	INST_VERSION=$(/opt/GitAhead/GitAhead --version 2>/dev/null | grep -o '[0-9][0-9.]*[0-9]')
	printf ' Instaled version: %s\n' "$INST_VERSION"
fi

printf '   Latest version: '
LATEST_LINK="https://github.com/gitahead/"$(wget -q4 -O - \
https://github.com/gitahead/gitahead/releases/latest | grep -o 'gitahead/releases/download/[^"]*\.sh')
LATEST_FILE=$(printf '%s' "$LATEST_LINK" | grep -o '[^/]*$')
if [ -z "$LATEST_FILE" ]; then
	printf 'unknown.\n\n'
	printf 'Check manualy at https://github.com/gitahead/gitahead/releases/latest\n\n'
	exit 1
fi
LATEST_VERSION=$(printf '%s' "$LATEST_FILE" | grep -o '[0-9][0-9.]*[0-9]')
printf '%s\n' "$LATEST_VERSION"
if [ "$INST_VERSION" ] && [ "$LATEST_VERSION" = "$INST_VERSION" ]; then
	printf '\nGitAhead is up to date.\n\n'
	exit
fi
printf '\n'

cd /opt
wget -4 -r -nd -nc --progress=dot:giga $LATEST_LINK || exit 1
[ -s "$LATEST_FILE" ] || exit 1

chmod 755 "$LATEST_FILE"
yes | ./"$LATEST_FILE"
rm -f ./"$LATEST_FILE"

if [ -s /opt/GitAhead/GitAhead ]; then
	mv -f /root/.local/share/applications/gitahead.desktop /usr/share/applications/
	cp -u /root/.local/share/icons/hicolor/16x16/apps/gitahead.png /usr/share/icons/hicolor/16x16/apps/
	cp -u /root/.local/share/icons/hicolor/32x32/apps/gitahead.png /usr/share/icons/hicolor/32x32/apps/
	cp -u /root/.local/share/icons/hicolor/64x64/apps/gitahead.png /usr/share/icons/hicolor/64x64/apps/
	cp -u /root/.local/share/icons/hicolor/128x128/apps/gitahead.png /usr/share/icons/hicolor/128x128/apps/
	cp -u /root/.local/share/icons/hicolor/256x256/apps/gitahead.png /usr/share/icons/hicolor/256x256/apps/
	cp -u /root/.local/share/icons/hicolor/512x512/apps/gitahead.png /usr/share/icons/hicolor/512x512/apps/
	ln -sf /opt/GitAhead/GitAhead /usr/local/bin/
fi

printf '\nDONE\n'
